// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testdata

import (
	mock "github.com/stretchr/testify/mock"
)

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type Store
func (_mock *Store) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Store_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Store_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Store_Expecter) Name() *Store_Name_Call {
	return &Store_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Store_Name_Call) Run(run func()) *Store_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Store_Name_Call) Return(s string) *Store_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Store_Name_Call) RunAndReturn(run func() string) *Store_Name_Call {
	_c.Call.Return(run)
	return _c
}

// RagSave provides a mock function for the type Store
func (_mock *Store) RagSave(content string, prepend string, part int) bool {
	ret := _mock.Called(content, prepend, part)

	if len(ret) == 0 {
		panic("no return value specified for RagSave")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string, int) bool); ok {
		r0 = returnFunc(content, prepend, part)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Store_RagSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RagSave'
type Store_RagSave_Call struct {
	*mock.Call
}

// RagSave is a helper method to define mock.On call
//   - content string
//   - prepend string
//   - part int
func (_e *Store_Expecter) RagSave(content any, prepend any, part any) *Store_RagSave_Call {
	return &Store_RagSave_Call{Call: _e.mock.On("RagSave", content, prepend, part)}
}

func (_c *Store_RagSave_Call) Run(run func(content string, prepend string, part int)) *Store_RagSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Store_RagSave_Call) Return(b bool) *Store_RagSave_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Store_RagSave_Call) RunAndReturn(run func(content string, prepend string, part int) bool) *Store_RagSave_Call {
	_c.Call.Return(run)
	return _c
}

// RagSearch provides a mock function for the type Store
func (_mock *Store) RagSearch(query string) string {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for RagSearch")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(query)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Store_RagSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RagSearch'
type Store_RagSearch_Call struct {
	*mock.Call
}

// RagSearch is a helper method to define mock.On call
//   - query string
func (_e *Store_Expecter) RagSearch(query any) *Store_RagSearch_Call {
	return &Store_RagSearch_Call{Call: _e.mock.On("RagSearch", query)}
}

func (_c *Store_RagSearch_Call) Run(run func(query string)) *Store_RagSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Store_RagSearch_Call) Return(s string) *Store_RagSearch_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Store_RagSearch_Call) RunAndReturn(run func(query string) string) *Store_RagSearch_Call {
	_c.Call.Return(run)
	return _c
}
