// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testdata

import (
	"github.com/sashabaranov/go-openai"
	mock "github.com/stretchr/testify/mock"
	"github.com/wmentor/go-magnetar/internal/config"
)

// NewAgentHandle creates a new instance of AgentHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentHandle {
	mock := &AgentHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AgentHandle is an autogenerated mock type for the AgentHandle type
type AgentHandle struct {
	mock.Mock
}

type AgentHandle_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentHandle) EXPECT() *AgentHandle_Expecter {
	return &AgentHandle_Expecter{mock: &_m.Mock}
}

// Compact provides a mock function for the type AgentHandle
func (_mock *AgentHandle) Compact() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Compact")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AgentHandle_Compact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compact'
type AgentHandle_Compact_Call struct {
	*mock.Call
}

// Compact is a helper method to define mock.On call
func (_e *AgentHandle_Expecter) Compact() *AgentHandle_Compact_Call {
	return &AgentHandle_Compact_Call{Call: _e.mock.On("Compact")}
}

func (_c *AgentHandle_Compact_Call) Run(run func()) *AgentHandle_Compact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AgentHandle_Compact_Call) Return(err error) *AgentHandle_Compact_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AgentHandle_Compact_Call) RunAndReturn(run func() error) *AgentHandle_Compact_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type AgentHandle
func (_mock *AgentHandle) Config() *config.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *config.Config
	if returnFunc, ok := ret.Get(0).(func() *config.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.Config)
		}
	}
	return r0
}

// AgentHandle_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type AgentHandle_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *AgentHandle_Expecter) Config() *AgentHandle_Config_Call {
	return &AgentHandle_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *AgentHandle_Config_Call) Run(run func()) *AgentHandle_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AgentHandle_Config_Call) Return(config1 *config.Config) *AgentHandle_Config_Call {
	_c.Call.Return(config1)
	return _c
}

func (_c *AgentHandle_Config_Call) RunAndReturn(run func() *config.Config) *AgentHandle_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Messages provides a mock function for the type AgentHandle
func (_mock *AgentHandle) Messages() []openai.ChatCompletionMessage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Messages")
	}

	var r0 []openai.ChatCompletionMessage
	if returnFunc, ok := ret.Get(0).(func() []openai.ChatCompletionMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]openai.ChatCompletionMessage)
		}
	}
	return r0
}

// AgentHandle_Messages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Messages'
type AgentHandle_Messages_Call struct {
	*mock.Call
}

// Messages is a helper method to define mock.On call
func (_e *AgentHandle_Expecter) Messages() *AgentHandle_Messages_Call {
	return &AgentHandle_Messages_Call{Call: _e.mock.On("Messages")}
}

func (_c *AgentHandle_Messages_Call) Run(run func()) *AgentHandle_Messages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AgentHandle_Messages_Call) Return(chatCompletionMessages []openai.ChatCompletionMessage) *AgentHandle_Messages_Call {
	_c.Call.Return(chatCompletionMessages)
	return _c
}

func (_c *AgentHandle_Messages_Call) RunAndReturn(run func() []openai.ChatCompletionMessage) *AgentHandle_Messages_Call {
	_c.Call.Return(run)
	return _c
}

// Reconfigure provides a mock function for the type AgentHandle
func (_mock *AgentHandle) Reconfigure() {
	_mock.Called()
	return
}

// AgentHandle_Reconfigure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconfigure'
type AgentHandle_Reconfigure_Call struct {
	*mock.Call
}

// Reconfigure is a helper method to define mock.On call
func (_e *AgentHandle_Expecter) Reconfigure() *AgentHandle_Reconfigure_Call {
	return &AgentHandle_Reconfigure_Call{Call: _e.mock.On("Reconfigure")}
}

func (_c *AgentHandle_Reconfigure_Call) Run(run func()) *AgentHandle_Reconfigure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AgentHandle_Reconfigure_Call) Return() *AgentHandle_Reconfigure_Call {
	_c.Call.Return()
	return _c
}

func (_c *AgentHandle_Reconfigure_Call) RunAndReturn(run func()) *AgentHandle_Reconfigure_Call {
	_c.Run(run)
	return _c
}

// Reset provides a mock function for the type AgentHandle
func (_mock *AgentHandle) Reset() {
	_mock.Called()
	return
}

// AgentHandle_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type AgentHandle_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *AgentHandle_Expecter) Reset() *AgentHandle_Reset_Call {
	return &AgentHandle_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *AgentHandle_Reset_Call) Run(run func()) *AgentHandle_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AgentHandle_Reset_Call) Return() *AgentHandle_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *AgentHandle_Reset_Call) RunAndReturn(run func()) *AgentHandle_Reset_Call {
	_c.Run(run)
	return _c
}

// SetMessages provides a mock function for the type AgentHandle
func (_mock *AgentHandle) SetMessages(chatCompletionMessages []openai.ChatCompletionMessage) {
	_mock.Called(chatCompletionMessages)
	return
}

// AgentHandle_SetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMessages'
type AgentHandle_SetMessages_Call struct {
	*mock.Call
}

// SetMessages is a helper method to define mock.On call
//   - chatCompletionMessages []openai.ChatCompletionMessage
func (_e *AgentHandle_Expecter) SetMessages(chatCompletionMessages any) *AgentHandle_SetMessages_Call {
	return &AgentHandle_SetMessages_Call{Call: _e.mock.On("SetMessages", chatCompletionMessages)}
}

func (_c *AgentHandle_SetMessages_Call) Run(run func(chatCompletionMessages []openai.ChatCompletionMessage)) *AgentHandle_SetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []openai.ChatCompletionMessage
		if args[0] != nil {
			arg0 = args[0].([]openai.ChatCompletionMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AgentHandle_SetMessages_Call) Return() *AgentHandle_SetMessages_Call {
	_c.Call.Return()
	return _c
}

func (_c *AgentHandle_SetMessages_Call) RunAndReturn(run func(chatCompletionMessages []openai.ChatCompletionMessage)) *AgentHandle_SetMessages_Call {
	_c.Run(run)
	return _c
}
