// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testdata

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/wmentor/go-magnetar/internal/plugin"
)

// NewHub creates a new instance of Hub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hub {
	mock := &Hub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Hub is an autogenerated mock type for the Hub type
type Hub struct {
	mock.Mock
}

type Hub_Expecter struct {
	mock *mock.Mock
}

func (_m *Hub) EXPECT() *Hub_Expecter {
	return &Hub_Expecter{mock: &_m.Mock}
}

// Go provides a mock function for the type Hub
func (_mock *Hub) Go(f func(ctx context.Context)) {
	_mock.Called(f)
	return
}

// Hub_Go_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Go'
type Hub_Go_Call struct {
	*mock.Call
}

// Go is a helper method to define mock.On call
//   - f func(ctx context.Context)
func (_e *Hub_Expecter) Go(f any) *Hub_Go_Call {
	return &Hub_Go_Call{Call: _e.mock.On("Go", f)}
}

func (_c *Hub_Go_Call) Run(run func(f func(ctx context.Context))) *Hub_Go_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(ctx context.Context)
		if args[0] != nil {
			arg0 = args[0].(func(ctx context.Context))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Hub_Go_Call) Return() *Hub_Go_Call {
	_c.Call.Return()
	return _c
}

func (_c *Hub_Go_Call) RunAndReturn(run func(f func(ctx context.Context))) *Hub_Go_Call {
	_c.Run(run)
	return _c
}

// RegisterChatCommand provides a mock function for the type Hub
func (_mock *Hub) RegisterChatCommand(cmd plugin.ChatCommand) {
	_mock.Called(cmd)
	return
}

// Hub_RegisterChatCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterChatCommand'
type Hub_RegisterChatCommand_Call struct {
	*mock.Call
}

// RegisterChatCommand is a helper method to define mock.On call
//   - cmd plugin.ChatCommand
func (_e *Hub_Expecter) RegisterChatCommand(cmd any) *Hub_RegisterChatCommand_Call {
	return &Hub_RegisterChatCommand_Call{Call: _e.mock.On("RegisterChatCommand", cmd)}
}

func (_c *Hub_RegisterChatCommand_Call) Run(run func(cmd plugin.ChatCommand)) *Hub_RegisterChatCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plugin.ChatCommand
		if args[0] != nil {
			arg0 = args[0].(plugin.ChatCommand)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Hub_RegisterChatCommand_Call) Return() *Hub_RegisterChatCommand_Call {
	_c.Call.Return()
	return _c
}

func (_c *Hub_RegisterChatCommand_Call) RunAndReturn(run func(cmd plugin.ChatCommand)) *Hub_RegisterChatCommand_Call {
	_c.Run(run)
	return _c
}

// RegisterPreprocessor provides a mock function for the type Hub
func (_mock *Hub) RegisterPreprocessor(fn plugin.PreprocessorFunc) {
	_mock.Called(fn)
	return
}

// Hub_RegisterPreprocessor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPreprocessor'
type Hub_RegisterPreprocessor_Call struct {
	*mock.Call
}

// RegisterPreprocessor is a helper method to define mock.On call
//   - fn plugin.PreprocessorFunc
func (_e *Hub_Expecter) RegisterPreprocessor(fn any) *Hub_RegisterPreprocessor_Call {
	return &Hub_RegisterPreprocessor_Call{Call: _e.mock.On("RegisterPreprocessor", fn)}
}

func (_c *Hub_RegisterPreprocessor_Call) Run(run func(fn plugin.PreprocessorFunc)) *Hub_RegisterPreprocessor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plugin.PreprocessorFunc
		if args[0] != nil {
			arg0 = args[0].(plugin.PreprocessorFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Hub_RegisterPreprocessor_Call) Return() *Hub_RegisterPreprocessor_Call {
	_c.Call.Return()
	return _c
}

func (_c *Hub_RegisterPreprocessor_Call) RunAndReturn(run func(fn plugin.PreprocessorFunc)) *Hub_RegisterPreprocessor_Call {
	_c.Run(run)
	return _c
}

// RegisterTool provides a mock function for the type Hub
func (_mock *Hub) RegisterTool(tool plugin.LLMTool) {
	_mock.Called(tool)
	return
}

// Hub_RegisterTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterTool'
type Hub_RegisterTool_Call struct {
	*mock.Call
}

// RegisterTool is a helper method to define mock.On call
//   - tool plugin.LLMTool
func (_e *Hub_Expecter) RegisterTool(tool any) *Hub_RegisterTool_Call {
	return &Hub_RegisterTool_Call{Call: _e.mock.On("RegisterTool", tool)}
}

func (_c *Hub_RegisterTool_Call) Run(run func(tool plugin.LLMTool)) *Hub_RegisterTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plugin.LLMTool
		if args[0] != nil {
			arg0 = args[0].(plugin.LLMTool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Hub_RegisterTool_Call) Return() *Hub_RegisterTool_Call {
	_c.Call.Return()
	return _c
}

func (_c *Hub_RegisterTool_Call) RunAndReturn(run func(tool plugin.LLMTool)) *Hub_RegisterTool_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type Hub
func (_mock *Hub) Stop() {
	_mock.Called()
	return
}

// Hub_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Hub_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Hub_Expecter) Stop() *Hub_Stop_Call {
	return &Hub_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Hub_Stop_Call) Run(run func()) *Hub_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Hub_Stop_Call) Return() *Hub_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *Hub_Stop_Call) RunAndReturn(run func()) *Hub_Stop_Call {
	_c.Run(run)
	return _c
}
