// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testdata

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wmentor/go-magnetar/internal/plugin"
)

// NewPlugin creates a new instance of Plugin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlugin(t interface {
	mock.TestingT
	Cleanup(func())
}) *Plugin {
	mock := &Plugin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Plugin is an autogenerated mock type for the Plugin type
type Plugin struct {
	mock.Mock
}

type Plugin_Expecter struct {
	mock *mock.Mock
}

func (_m *Plugin) EXPECT() *Plugin_Expecter {
	return &Plugin_Expecter{mock: &_m.Mock}
}

// Init provides a mock function for the type Plugin
func (_mock *Plugin) Init(s *plugin.State, hub plugin.Hub) error {
	ret := _mock.Called(s, hub)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*plugin.State, plugin.Hub) error); ok {
		r0 = returnFunc(s, hub)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Plugin_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type Plugin_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - s *plugin.State
//   - hub plugin.Hub
func (_e *Plugin_Expecter) Init(s any, hub any) *Plugin_Init_Call {
	return &Plugin_Init_Call{Call: _e.mock.On("Init", s, hub)}
}

func (_c *Plugin_Init_Call) Run(run func(s *plugin.State, hub plugin.Hub)) *Plugin_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *plugin.State
		if args[0] != nil {
			arg0 = args[0].(*plugin.State)
		}
		var arg1 plugin.Hub
		if args[1] != nil {
			arg1 = args[1].(plugin.Hub)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Plugin_Init_Call) Return(err error) *Plugin_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Plugin_Init_Call) RunAndReturn(run func(s *plugin.State, hub plugin.Hub) error) *Plugin_Init_Call {
	_c.Call.Return(run)
	return _c
}
