// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testdata

import (
	mock "github.com/stretchr/testify/mock"
)

// NewCodec creates a new instance of Codec. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodec(t interface {
	mock.TestingT
	Cleanup(func())
}) *Codec {
	mock := &Codec{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Codec is an autogenerated mock type for the Codec type
type Codec struct {
	mock.Mock
}

type Codec_Expecter struct {
	mock *mock.Mock
}

func (_m *Codec) EXPECT() *Codec_Expecter {
	return &Codec_Expecter{mock: &_m.Mock}
}

// ReadFile provides a mock function for the type Codec
func (_mock *Codec) ReadFile(filename string) (string, error) {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(filename)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(filename)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Codec_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type Codec_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - filename string
func (_e *Codec_Expecter) ReadFile(filename any) *Codec_ReadFile_Call {
	return &Codec_ReadFile_Call{Call: _e.mock.On("ReadFile", filename)}
}

func (_c *Codec_ReadFile_Call) Run(run func(filename string)) *Codec_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Codec_ReadFile_Call) Return(s string, err error) *Codec_ReadFile_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Codec_ReadFile_Call) RunAndReturn(run func(filename string) (string, error)) *Codec_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}
