package config

import (
	"fmt"
	"log/slog"
	"os"

	"github.com/knadh/koanf/parsers/yaml"
	"github.com/knadh/koanf/providers/confmap"
	"github.com/knadh/koanf/providers/file"
	"github.com/knadh/koanf/v2"
	"github.com/lmittmann/tint"
)

// LLMConfig holds settings for the main chat LLM.
type LLMConfig struct {
	BaseURL string `koanf:"base_url"`
	APIKey  string `koanf:"api_key"`
	Model   string `koanf:"model"`
	Context int    `koanf:"context"`
}

// EmbeddingConfig holds settings for the embedding model used in RAG.
type EmbeddingConfig struct {
	BaseURL    string `koanf:"base_url"`
	APIKey     string `koanf:"api_key"`
	Model      string `koanf:"model"`
	VectorSize int    `koanf:"vector_size"`
}

// QdrantConfig holds connection settings for Qdrant.
type QdrantConfig struct {
	ConnStr    string `koanf:"connstr"`
	Collection string `koanf:"collection"`
}

// ChunkConfig holds chunking parameters for indexing.
type ChunkConfig struct {
	Size    int `koanf:"size"`
	Overlap int `koanf:"overlap"`
}

// WebFetchConfig holds settings for web fetch preprocessing.
type WebFetchConfig struct {
	BaseURL string `koanf:"base_url"`
	APIKey  string `koanf:"api_key"`
	Model   string `koanf:"model"`
	Context int    `koanf:"context"`
}

// SearchConfig holds retrieval parameters for RAG search.
type SearchConfig struct {
	Limit     int     `koanf:"limit"`     // maximum number of results to return
	Threshold float32 `koanf:"threshold"` // minimum cosine-similarity score (0–1)

	// MultiQuery is the number of additional query reformulations generated by
	// the LLM to improve recall. 0 disables multi-query (single search only).
	// Recommended range: 1–3. Each extra query adds one embedding + one Qdrant
	// call, so higher values increase latency proportionally.
	MultiQuery int `koanf:"multi_query"`

	// DedupThreshold is the minimum cosine similarity between two result chunks
	// at which the lower-scoring chunk is discarded as a near-duplicate.
	// 0 disables deduplication. Recommended: 0.92–0.95.
	DedupThreshold float32 `koanf:"dedup_threshold"`
}

// RAGConfig combines embedding model, chunking, search and Qdrant settings.
type RAGConfig struct {
	LLM    EmbeddingConfig `koanf:"llm"`
	Qdrant QdrantConfig    `koanf:"qdrant"`
	Chunk  ChunkConfig     `koanf:"chunk"`
	Search SearchConfig    `koanf:"search"`
}

// LogConfig holds logging settings.
type LogConfig struct {
	Level string `koanf:"level"` // debug | info | warn | error
}

// ConfluenceConfig holds settings for Confluence integration.
type ConfluenceConfig struct {
	BaseURL string `koanf:"base_url"`
	APIKey  string `koanf:"api_key"`
}

// JIRAConfig holds settings for JIRA integration.
type JIRAConfig struct {
	BaseURL string `koanf:"base_url"`
	APIKey  string `koanf:"api_key"`
}

// CompactConfig controls the history-summarization behaviour of the chat agent.
type CompactConfig struct {
	// Threshold is the token count at which history summarization is triggered.
	// If zero or negative, defaults to 80 % of LLM.Context.
	Threshold int `koanf:"threshold"`

	// SaveTail is the number of most-recent messages to preserve unchanged
	// during summarization. If less than 1, all messages are passed to the
	// summarizer.
	SaveTail int `koanf:"save_tail"`
}

// Config is the root configuration structure.
type Config struct {
	LLM        LLMConfig        `koanf:"llm"`
	RAG        RAGConfig        `koanf:"rag"`
	Log        LogConfig        `koanf:"log"`
	Compact    CompactConfig    `koanf:"compact"`
	WebFetch   WebFetchConfig   `koanf:"webfetch"`
	Confluence ConfluenceConfig `koanf:"confluence"`
	JIRA       JIRAConfig       `koanf:"jira"`
}

// defaults holds default config values that are applied before the
// YAML file is loaded, so the user doesn't need to set them.
var defaults = map[string]any{
	"rag.chunk.size":             512,  // runes; matches DefaultConfig in internal/chunk
	"rag.chunk.overlap":          64,   // runes; ~12.5% overlap is the RAG sweet-spot
	"rag.search.limit":           10,   // top-N results per query
	"rag.search.threshold":       0.40, // minimum cosine-similarity score
	"rag.search.multi_query":     2,    // number of extra query reformulations
	"rag.search.dedup_threshold": 0.95, // near-duplicate suppression threshold
}

// Load reads and parses a YAML config file at the given path.
func Load(path string) (*Config, error) {
	k := koanf.New(".")

	if err := k.Load(confmap.Provider(defaults, "."), nil); err != nil {
		return nil, fmt.Errorf("config: failed to load defaults: %w", err)
	}

	if err := k.Load(file.Provider(path), yaml.Parser()); err != nil {
		return nil, fmt.Errorf("config: failed to load %q: %w", path, err)
	}

	cfg := &Config{}
	if err := k.Unmarshal("", cfg); err != nil {
		return nil, fmt.Errorf("config: failed to unmarshal: %w", err)
	}

	return cfg, nil
}

// SetupLogger initialises the global slog logger based on the config level.
// Output is written to stderr using tint for colourised, human-readable formatting.
func SetupLogger(cfg *Config) {
	var level slog.Level

	switch cfg.Log.Level {
	case "debug":
		level = slog.LevelDebug
	case "warn":
		level = slog.LevelWarn
	case "error":
		level = slog.LevelError
	default:
		level = slog.LevelInfo
	}

	handler := tint.NewHandler(os.Stderr, &tint.Options{
		Level:   level,
		NoColor: !isTerminal(os.Stderr),
	})
	slog.SetDefault(slog.New(handler))
}

// isTerminal reports whether f is connected to a terminal.
func isTerminal(f *os.File) bool {
	fi, err := f.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}
